### PR TITLE
Add show-ranges class to datepicker

### PR DESCRIPTION
**Pull request by RoM4iK**
Hi! In this PR I want to add a `show-ranges` class to the daterangepicker container when ranges tab is visible. The class will apply if ranges list or apply/cancel button is visible.
The general purpose of this class is a CSS customization of daterangepicker.

### CODE REVIEW

**Comment by RoM4iK** [comment]
@dangrossman can you review this one, please?

**Comment by dangrossman** [comment]
If you need this for yourself, you don't need me to merge it to start using it. I am changing the whole template in the next version, so it won't really matter.

**Comment by RoM4iK** [comment]
It's consistent with current `show-calendar` class, so I think there are no problems to have this in this `2.x` versions if you are talking about the major release.
I'm sorry because I don't know your future release plans, but I will be happy if this one will be released in the next minor release.

**Comment by dangrossman** [comment]
Merged manually

**Comment by krasnoukhov** [comment]
@dangrossman Are you going to include this change in 2.x version? Thanks

**Pull request closed without merging**
